name: Deploy to Remote Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 198.211.97.11
          username: phoenix
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/drusite
            git pull origin master
            composer install --no-dev --optimize-autoloader
            drush updb -y
            drush cr
